# Versioning System
PRODUCT_VERSION_NAME = MASTER
PRODUCT_VERSION_MAJOR = KitKat
PRODUCT_VERSION_MINOR = 5

MOD_VERSION := deedwar-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(PRODUCT_VERSION_NAME)

PRODUCT_PROPERTY_OVERRIDES += \
  ro.mod.version=$(MOD_VERSION)
